### ISSUE TITLE
Currency: Space between currency symbol and numbers breaks IA triggering

### ISSUE THREAD

**Issue by jkanarek** [duckduckgo/zeroclickinfo-spice#2235] opened 2015-10-20 15:36 UTC
~~A lot of countries use commas (€ 889,00) rather than decimal points, but this IA doesn't seem to support commas.~~

When a space separates the currency symbol and the digits, this IA doesn't trigger as expected:
- https://yahoo.duckduckgo.com/?q=%E2%82%AC+889%2C00
- https://yahoo.duckduckgo.com/?q=%24+127 (in this case we end up show a movie result, which is bad!)

Let's relax the triggering slightly to allow for at least a single space between a leading/trailing currency symbol and the numbers

------
IA Page:  http://duck.co/ia/view/currency

**Comment by moollaza** [comment] 2015-10-21 15:22
@jkanarek it looks like the issue is actually the space between the `€` and the numbers,  `889,00`

If you remove the space, it works as expected: https://yahoo.duckduckgo.com/?q=%E2%82%AC889%2C00&ia=currency

I'll update this issue to reflect the proper fix.

**Comment by altern8tif** [comment] 2015-12-13 10:53
This looks like it's good to close... Not sure why Github didn't auto-closed upon PR merge though.

**Comment by jorisoverzet** [comment] 2015-12-17 17:36
Agree with @altern8tif , this one can be closed and marked as fixed.

**Closed** 2015-12-17 22:23 UTC
Labels: Bug, Low-Hanging Fruit, Triggering
