### ISSUE TITLE
"time" probably shouldn't trigger Timer.pm but trigger Time.pm instead

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1671] opened 2015-03-23 19:43 UTC
Anybody have any other opinion on this?

![screen shot 2015-03-23 at 3 42 02 pm](https://cloud.githubusercontent.com/assets/81969/6788952/47db025a-d173-11e4-850e-354d3c13c2d7.png)

**Comment by moollaza** [comment] 2015-03-24 13:29
@jagtalon this is a bug. I believe a fix has already been merged to address this.

**Comment by moollaza** [comment] 2015-03-24 13:30
Also, this is a duplicate of https://github.com/duckduckgo/zeroclickinfo-spice/issues/1640

**Closed by moollaza** 2015-03-24 13:30 UTC
Labels: Improvement
