### ISSUE TITLE
Time: Trigger for timezone queries

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#3108] opened 2017-01-21 14:58 UTC
We get a fair amount of requests for this to trigger on searches for time zones. It would be nice to add that.

User Feedback with examples:

**PST time**
[https://duckduckgo.com/?q=PST%20time&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=PST%20time&kp=1&kad=wt_WT&kl=wt-wt)
_"I would like an instant answer with the current time in PST timezone"_

**Pacific Time**
[https://duckduckgo.com/?q=Pacific%20Time&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=Pacific%20Time&kp=1&kad=wt_WT&kl=wt-wt)
_Would be cool to have a the current time of this zime zone displayed."_

**eastern time**
[https://duckduckgo.com/?q=eastern%20time&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=eastern%20time&kp=1&kad=wt_WT&kl=wt-wt)
_"it would be nice if a query for a time zone displays the current time in that time zone."_

**utc**
[https://duckduckgo.com/?q=utc&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=utc&kp=1&kad=wt_WT&kl=wt-wt)
_It would be very nice if searching for a timezone showed you what time it was there. Or, "what time is it," same._ 

**current utc time**
[https://duckduckgo.com/?q=current%20utc%20time&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=current%20utc%20time&kp=1&kad=wt_WT&kl=wt-wt)
_"I want to know the current time in UTC."_

------
IA Page:  http://duck.co/ia/view/time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by MrChrisW** [comment] 2017-01-27 05:03
Duplicate of https://github.com/duckduckgo/zeroclickinfo-spice/issues/1802

**Closed by MrChrisW** 2017-01-27 05:03 UTC
