### ISSUE TITLE
Forecast: Searching for Tel Aviv returns weather for Chicago

### ISSUE THREAD

**Issue by cascer1** [duckduckgo/zeroclickinfo-spice#3560] opened 2018-11-03 18:58 UTC
searching for `weather for Tel Aviv` and `weather for Tel Aviv Israel` returns the weather forecast for Chicago, IL.

I expected to receive the weather forecats of Tel Aviv, Israel.

![image](https://user-images.githubusercontent.com/7243299/47956304-b0e08400-dfa2-11e8-9d72-60f9d9379ab6.png)

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by moollaza** [comment] 2018-11-07 16:21
@cascer1 thanks for reporting. We are aware of the issue and currently working on a fix. Marking as duplicate of #3561 where I am combining similar issues.

**Closed by moollaza** 2018-11-07 16:21 UTC
Labels: Bug, Internal, Relevancy

**Comment by moollaza** [comment] 2018-11-07 16:23
Duplicate of #3561
