### ISSUE TITLE
News: Searched for "Top Stories" instead of searching for keyword

### ISSUE THREAD

**Issue by shrikant-joshi** [duckduckgo/zeroclickinfo-spice#2370] opened 2016-01-03 12:32 UTC
Just tried searching for "Israil Gurung" and then clicked the "News" zero-click info section and got this very interesting set of results:

![bug israilgurungdogozeroclicknews](https://cloud.githubusercontent.com/assets/2922898/12078728/4f80bc5a-b243-11e5-946f-f26b749a17cc.png)

As you can see, the zero-click seems to have searched the source for "Top Stories" instead of searching for the keywords "Israil Gurung". My theory is that if no news is found for a particular set of keywords, the default set of keywords is "Top Stories" - tried looking through the code but I am a newbie and not very well-versed, hence posting an issue. Apologies for the trouble.

Thanks for reading and cheers!

------
IA Page:  http://duck.co/ia/view/news

**Comment by MrChrisW** [comment] 2016-01-04 09:23
Hi @shrikant-joshi thanks for lodging an issue report. I've been able to replicate what you've described, this seems to be internal and expected behavior. 

The following happens when you search that term: 

+ Dynamically generated JS file `https://duckduckgo.com/d.js?q=Israil%20Gurung` is included on the page. This contains a call to `DDG.duckbar.addDeferred` method specifying the following:

`DDG.duckbar.addDeferred('news',["Israil%20Gurung","israil%20gurung","top+stories"])`

+ News will defer/fallback to the quires specified above if nothing is returned by the news IA for that query https://duckduckgo.com/news.js?l=us-en&o=json&q=Israil%20Gurung

![2016-01-04-33-israil gurung at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/12086643/0bed34b8-b307-11e5-8124-645c99b0ccb1.png)

I'd say this behavior is intended as removing/showing a blank news IA is not user/UI friendly.  

@moollaza @jagtalon Can you confirm this behavior is tolerated?

**Comment by moollaza** [comment] 2016-01-12 00:13
@MrChrisW good question! I believe you're correct, but I think @tommytommytommy would know best...

**Comment by tommytommytommy** [comment] 2016-01-12 00:16
@MrChrisW @moollaza The description is spot on...I would add more detail, but I don't think that there's anything left to add.

**Comment by edgesince84** [comment] 2016-07-25 18:34
If this is expected behavior, I'm going to close this one out!  thanks

**Closed by edgesince84** 2016-07-25 18:34 UTC
Labels: Internal, Relevancy, Tolerated
