### ISSUE TITLE
Bike Sharing Philadelphia (Indego): 

### ISSUE THREAD

**Issue by AcriCAA** [duckduckgo/zeroclickinfo-spice#3441] opened 2017-10-14 11:57 UTC
Looks like this is down again. @moollaza 

------
IA Page:  http://duck.co/ia/view/bike_sharing_indego_phl 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @AcriCAA

**Comment by moollaza** [comment] 2017-10-25 17:07
Duplicate of #3450

**Closed** 2017-10-25 17:06 UTC
