### ISSUE TITLE
Forecast: Weather result is for an unrelated city

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-spice#2362] opened 2015-12-28 01:19 UTC
As [reported on Twitter](https://twitter.com/hugoroyd/status/680840976584282112), a search for "weather paris" shows the weather for "Saint-Christophe-d'Allier". Happens on both mobile and desktop regardless of whether the region is set.

![forecast-paris-mobile](https://cloud.githubusercontent.com/assets/94173/12012876/599f738a-ad4c-11e5-9679-ce4e8dfd06d1.png)

![forecast-paris-desktop](https://cloud.githubusercontent.com/assets/94173/12012869/215258a8-ad4c-11e5-96ea-1fdaa6de992e.png)

---

IA Page:  http://duck.co/ia/view/forecast

**Comment by preemeijer** [comment] 2015-12-28 10:42
I've tried it myself today, because there is a similar problem for sunset (#2354) and I'm trying similar searches and I get the following (correct) results. Weird stuff.
![weather-france](https://cloud.githubusercontent.com/assets/356869/12017517/f2bfd252-ad57-11e5-88aa-9b20a0149288.png)
![weather-netherlands](https://cloud.githubusercontent.com/assets/356869/12017519/f5e2ee60-ad57-11e5-9494-242e0d626912.png)
![weather-paris](https://cloud.githubusercontent.com/assets/356869/12017520/f8945108-ad57-11e5-9494-a0a1b48bf0d7.png)
![weather-amsterdam](https://cloud.githubusercontent.com/assets/356869/12017523/fc110894-ad57-11e5-99a9-2b6a484591a3.png)

**Comment by preemeijer** [comment] 2015-12-28 10:45
When I enable Region most of the results are correct, except when I use the search from above for weather netherlands ... then I get the following back:
![weather-netherlands-region-on](https://cloud.githubusercontent.com/assets/356869/12017545/730bea2c-ad58-11e5-9fd3-cb10485cdc4d.png)

**Comment by moollaza** [comment] 2015-12-29 17:48
@tagawa I'm unable to reproduce the Paris bug -- are you still seeing that?

@preemeijer the same goes for Netherlands and Amsterdam, I'm getting correct results.

**Comment by preemeijer** [comment] 2015-12-29 19:03
@moollaza yes I still get the same result but only if I set my current region to Netherlands. 
If I set my current region to United States there is no problem and I get the right results.

**Comment by GuiltyDolphin** [comment] 2016-01-01 21:47
@moollaza @tagawa I'm getting a similar issue, if I just search for `weather` it gives the correct results for my location - but when I search for something like `weather in {Various English Counties and Cities}` it is giving me the results for American cities of the same name!

**Comment by moollaza** [comment] 2016-01-06 06:26
@preemeijer it looks like that may have been cached please try https://duckduckgo.com/?q=weather+the+netherlands&t=ffab&ia=weather - with your region set (which I don't think should affect results..)

**Comment by preemeijer** [comment] 2016-01-06 06:56
@moollaza if I try your link I indeed get Soest in the Netherlands (not Amsterdam) but if I search for weather netherlands I get Weather for St John's, NL.
I don't have any history in my browser.

When I copy/paste this Weather for St John's, NL I get Weather for St John, IN

**Comment by tagawa** [comment] 2016-10-26 09:09
Another example reported by a user - a search for "the weather in kobe, japan" shows the weather for Villa Corona, Mexico:
https://duckduckgo.com/?q=the+weather+in+kobe%2C+japan&ia=weather

**Comment by mrshu** [comment] 2016-11-01 20:10
Can you please see whether this problem is still a valid issue?

The internal triggering has changed a bit and all of the issues described here should be now fixed.

**Comment by githubtefo** [comment] 2017-02-21 03:16
Same here from "Weather in Sao Paulo" and "Weather in New York".

**Comment by moollaza** [comment] 2017-10-09 23:46
Closing. Duplicate of #899

**Closed by moollaza** 2017-10-09 23:46 UTC
Labels: Bug, Relevancy
