### ISSUE TITLE
Wrong temperature unit in forecast switch

### ISSUE THREAD

**Issue by LexLuengas** [duckduckgo/zeroclickinfo-spice#1760] opened 2015-04-14 07:55 UTC
If my default temperature unit is C°, the forecast IA is updated correctly, but the switch is not. Clicking on the switch also activates the inverse temperature unit. (I guess it has something to do with calling `updateTempSwitch(uom)` properly somewhere near [line 379](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L379), but I'm new here, so I don't want to break anything)
![wrongtunits](https://cloud.githubusercontent.com/assets/3997377/7131964/178d0d28-e285-11e4-8ae7-0a486238b8d4.png)

**Comment by MrChrisW** [comment] 2015-04-14 10:42
Hi @LexLuengas thanks for reporting this issue, however I believe this feature is by design. 

The [`fe_temp_switch`](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L385) div calls `updateUnitOfMeasure()` when clicked, this includes both the 
[&deg;F and &deg;C](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.handlebars#L9-L11)

@mattr555 any comment?



![out](https://cloud.githubusercontent.com/assets/5282264/7135061/99d4dc34-e2d5-11e4-966c-0a1190903944.gif)

**Comment by mattr555** [comment] 2015-04-14 11:26
Yeah, this is by design. When designing a toggle, it's hard to choose either to highlight the unit being chosen or the unit being currently used, but I think we made the most functional choice.

**Comment by moollaza** [comment] 2015-04-14 13:31
Closing this as technically everything is correct. I'll mention this to the design team though -- maybe we can design a more obvious toggle.

Thanks guys!

**Closed by moollaza** 2015-04-14 13:31 UTC
Labels: Design, Tolerated
