### ISSUE TITLE
Quixey: Investigate missing image

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#1426] opened 2015-01-17 00:36 UTC
![screen shot 2015-01-16 at 7 35 54 pm](https://cloud.githubusercontent.com/assets/81969/5786666/fe11b23a-9db6-11e4-911f-74a4cfc63a8f.png)

**Comment by adentranter** [comment] 2015-01-18 13:27
I just tried to confirm whether this was an issue and the image loaded for me.
Image is Attached.
![screenshot from 2015-01-18 23 26 24](https://cloud.githubusercontent.com/assets/3243476/5792546/821c08c4-9f69-11e4-88cc-ac2b72307666.png)

**Comment by puskin94** [comment] 2015-01-19 14:31
The image in my test is loaded correctly, try to delete your browser's cache

**Comment by MrChrisW** [comment] 2015-01-21 01:21
Closing as unable to reproduce. 

Possible intermittent error with DDG Proxy or Cloudfront. Image is loadable directly: 
https://images.duckduckgo.com/iu/?u=https://d1z22zla46lb9g.cloudfront.net/image/3014509770&f=1

**Closed by MrChrisW** 2015-01-21 01:21 UTC
Labels: Bug
