### ISSUE TITLE
Timer: continues to wiggle after alarm sound has been dismissed

### ISSUE THREAD

**Issue by thistleBgood** [duckduckgo/zeroclickinfo-spice#2625] opened 2016-03-26 18:56 UTC
Had multiple instant answer timers open at once, only one counting down. When it ran out, it did the usual notification of making a trilling sound and wiggling back and forth. I think I clicked somewhere in the instant answers area, somewhere within the red box shown on the attached image. When I did so, the sound stopped and it reverted to the display shown in the picture, but it continued wiggling back and forth. Eventually I clicked somewhere else and it stopped, but that was after several minutes of it wiggling.

![screenshot from 2016-03-26 18 50 18](https://cloud.githubusercontent.com/assets/9945739/14061865/e504a828-f383-11e5-9a67-04384cce54ac.png)

Issue occurred on the following platform: Chromium Version 49.0.2623.87 Ubuntu 14.04 (64-bit)

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by GuiltyDolphin** [comment] 2016-03-26 19:00
@thistleBgood I noticed this once when adding a countdown to the tab name... Never saw it happen since. Have you managed to reproduce the behavior?

**Comment by thistleBgood** [comment] 2016-03-26 22:22
Unfortunately not. I was surprised to encounter it, and wasn't paying attention to where I was clicking, hence the imprecise boundaries of the box in the screenshot. I tried to get it to work with other timers in other tabs but they behaved properly every time I did.

**Comment by GuiltyDolphin** [comment] 2016-03-27 08:55
@thistleBgood Hmm... Are you at all versed in JS? If so, the appropriate code (I believe) is the [shake function](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/timer/timer.js#L94). I'll have a peer myself and let you know if I spot anything weird.

**Comment by moollaza** [comment] 2016-03-28 14:05
@thistleBgood @GuiltyDolphin It looks like clicking outside the tile stops the animation but doesn't reset the tile from the "completed" state (green checkmark).

Definitely an issue around the click handler

**Comment by mattr555** [comment] 2016-03-31 01:05
Definitely hard to track this one down! I'll try to fix this one and another bug I found (timer starts automatically if you close all timers and open another, with a specified time in the query) early next week.

**Comment by mattr555** [comment] 2016-04-06 01:59
@thistleBgood @GuiltyDolphin sorry, I still can't reproduce this. The idea is to stop the sound and shaking when there is a click on the screen, but keep the checkmark until the user explicitly clicks on that. If this bug is rare can we tolerate it?

**Comment by GuiltyDolphin** [comment] 2016-04-06 09:30
@mattr555 My DuckPAN is being a bit off lately and I can't reproduce it on production.

I'm happy to have it `Tolerated` - at least for now (it isn't a huge issue); if we get more reports we can look into it further - my guess is it might be managing to click at the same time as a loop starts/stops? Something difficult to do.

**Comment by edgesince84** [comment] 2016-07-25 19:06
I'm also unable to reproduce this issue, so I'm going to close it out for now.  If anyone can reproduce it, feel free to open it back up.  thanks!

**Closed by edgesince84** 2016-07-25 19:06 UTC
Labels: Bug, Design, Maintainer Approved, Tolerated
