### ISSUE TITLE
Location Lat/Lon NaN

### ISSUE THREAD

**Issue by Cameleopardus** [duckduckgo/zeroclickinfo-spice#2208] opened 2015-09-28 21:47 UTC
Don't know if this is the correct place for this, but the issue is with spice maps.

searching for lat/lon of a location will return map, with popover where lat/lon is NaN
Info from server is in correct format: "Point","coordinates":[-122.7282,45.5801]}

Example:
https://duckduckgo.com/?q=Portland+oregon+latitude&ia=maps

Screenshot:
http://i.imgur.com/AL00j81.png

**Comment by moollaza** [comment] 2015-10-05 21:41
@Cameleopardus thanks a lot for reporting this! I've made a task for the team to investigate

**Comment by Jedidiah** [comment] 2015-12-02 00:59
Has this been fixed? I can't reproduce it.

**Comment by MrChrisW** [comment] 2015-12-02 01:02
@Jedidiah Looks like it's been fixed internally! Will close this off now  :+1: 

![2015-12-02-52-portland oregon latitude at duckduckgo](https://cloud.githubusercontent.com/assets/5282264/11519229/59b4006c-98d3-11e5-8f3a-f47a0be515d2.png)

**Comment by Jedidiah** [comment] 2015-12-02 01:54
Great :+1:

**Closed** 2015-12-02 18:07 UTC
Labels: Bug, Internal, Priority: High
