### ISSUE TITLE
Time: No results returned for query "hawaii time"

### ISSUE THREAD

**Issue by strugee** [duckduckgo/zeroclickinfo-spice#1976] opened 2015-06-30 05:55 UTC
E.g. if I search "london time" it should return the same results as "time in london".

____
https://duck.co/ia/view/time

**Comment by gokul1794** [comment] 2015-06-30 06:19
Hey @strugee, this seems to work for me ![londontime](https://cloud.githubusercontent.com/assets/6311809/8424908/f8cd208c-1f1d-11e5-8a1d-d9d5c1defff5.png)

**Comment by strugee** [comment] 2015-07-02 00:00
I'm sorry, that's my fault. I made up "london" without testing first, and I got the details wrong. The actual bug is that a search for "hawaii time" should bring up some useful result, since Hawaii is entirely in one time zone.

(I assumed that that wasn't the problem, based on [this comment][1], but clearly I was wrong.)

 [1]: https://github.com/duckduckgo/zeroclickinfo-spice/blob/a16fcae8a3a57daafc4321486a3e8ff66ae1634a/lib/DDG/Spice/Time.pm#L11

**Comment by MrChrisW** [comment] 2015-07-06 13:31
@strugee Thanks for reporting this. 
Can confirm, with the queries for the time IA:
+ [hawaii time](https://duckduckgo.com/?q=hawaii+time) - result returned
+ [time hawaii](https://duckduckgo.com/?q=time+hawaii)-  no result

It looks like the IA is triggering correctly for both queries, however the **country to capital city translation** is causing problems. 

Example the query **time hawaii** sends a request for [Honolulu, Hawaii, united states](https://duckduckgo.com/js/spice/time/Honolulu%2C%20Hawaii%2C%20united%20states) to the API. However the **hawaii time**  query requests [united states hawaii](https://duckduckgo.com/js/spice/time/united%20states%20hawaii) this causes the relevancy checking to fail.

**Comment by strugee** [comment] 2015-07-07 03:01
> hawaii time - result returned

I can't reproduce this. All I see is the Wikipedia article on the timezone.

**Comment by MrChrisW** [comment] 2015-07-07 03:44
@strugee Sorry but them the wrong way around! `hawaii time` does not return a result.

**Comment by moollaza** [comment] 2015-07-23 02:34
As @MrChrisW pointed out the problem is due to the relevancy checking approach we've used. This will be fixed shortly as it's caused several problems for this IA.

**Comment by MrChrisW** [comment] 2016-01-04 12:26
Closing this now, keeping track of this in #1730 . Thanks @strugee

**Closed by MrChrisW** 2016-01-04 12:26 UTC
Labels: Bug, Relevancy, Triggering
