### ISSUE TITLE
Similar Websites: 'Similar Site' to... (singular) doesn't trigger the IA

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2023] opened 2015-07-10 16:14 UTC
Can we add 'similar site' as a trigger?

cc @moollaza 
------
IA Page:  http://duck.co/ia/view/similar_sites

**Comment by moollaza** [comment] 2015-07-10 20:31
Closing as duplicate of #2024

**Closed by moollaza** 2015-07-10 20:31 UTC
