### ISSUE TITLE
Forecast: Mexican cities completely mixed up

### ISSUE THREAD

**Issue by platschi** [duckduckgo/zeroclickinfo-spice#2575] opened 2016-03-12 15:43 UTC
When searching various Mexican cities for weather data, DDG shows me completely different data for random other cities in the country which are far away from the originally searched location.

Example searches: `weather in Cancún`, `weather in Cozumel`, `weather in Tulum`, `weather in Acapulco`

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

**Comment by himanshu0113** [comment] 2016-03-12 20:12
Thankyou @platschi for the information.

@moollaza I checked Forecast.io and the site itself is giving diffrent results for the mexican cities. Probably the the query sending the city name in the API call is also not working correctly. I am not very sure on how to proceed. Any help?

**Comment by moollaza** [comment] 2016-03-14 15:28
Part of the problem seems to be coming from the city we're sending the query -- right now this Instant Answer uses our internal "deep" triggering which leverages the organic links to determine a location for the API. In the case of `Cancun` we're sending `cancun mexico mx` -- the `mx` seems to alter the city and causes incorrect information.

Their API doesn't seem to have specific information for Cancun though and gives a different city when we just send them `cancun` as the input location.

**Comment by edgesince84** [comment] 2016-07-25 18:53
this issue is a duplicate of https://github.com/duckduckgo/zeroclickinfo-spice/issues/2362 and we'll be working toward addressing it!  thanks

**Closed by edgesince84** 2016-07-25 18:53 UTC
Labels: Bug, External, Internal, Triggering
