### ISSUE TITLE
RubyGems: Not working

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2247] opened 2015-10-27 12:51 UTC
Their API endpoint works: https://rubygems.org/api/v1/search.json?query=rspec

But calls through spice always return no results:
https://duckduckgo.com/?q=rubygems+rspec
https://duckduckgo.com/js/spice/ruby_gems/rspec

cc @moollaza @malbin @russellholt 

------
IA Page:  http://duck.co/ia/view/ruby_gems

**Comment by moollaza** [comment] 2015-10-27 14:47
@bsstoner this one has stumped me. Will need further investigation...

**Comment by moollaza** [comment] 2015-10-27 14:48
FWIW the IA works in DuckPAN, so this is an internal problem.

**Comment by andrey-p** [comment] 2015-10-28 10:55
Confirmed, it's internal. Will have a look.

**Comment by andrey-p** [comment] 2015-10-28 11:24
Sorry, I jumped the gun and thought it was an internal frontend issue. It's not IP blocking, otherwise running DuckPAN locally will have led to the same problem. Some kind of metadata issue?

**Comment by altern8tif** [comment] 2015-11-02 10:58
@andrey-p @bsstoner @moollaza this seems to be working now... I supposed it was resolved internally?

**Comment by moollaza** [comment] 2015-11-02 15:50
@altern8tif yup I updated the code. We had both `wrap_jsonp_callback` and `&callback=` so we were double-wrapping the API Response!

**Closed by moollaza** 2015-11-02 15:50 UTC
Labels: Internal, Priority: High
