### ISSUE TITLE
Airlines: does not respond to lowercase flight code

### ISSUE THREAD

**Issue by peterakkies** [duckduckgo/zeroclickinfo-spice#2352] opened 2015-12-23 19:55 UTC
Hi everyone,

My apologies is this is not the right way to bring up this issue.

I noticed that the DuckDuckGo flight information only responds to flight codes entered using uppercase letters, e.g. "AC824" but not "ac824". Is this intentional? I imagine many users would use the lowercase.

Regards,
Peter
------
IA Page:  http://duck.co/ia/view/airlines

**Comment by marianosimone** [comment] 2015-12-25 02:26
I'm not seeing this behaviour. Both https://duckduckgo.com/?q=ua+244 and https://duckduckgo.com/?q=UA+244 seem to work just fine, and neither AC824 nor ac824 find Air Canada flights.

I'm not sure I understand what's going on, but it seems like this IA was disabled https://github.com/duckduckgo/zeroclickinfo-spice/commit/ba91e55271c856a76ac621047805a184cf220e9a (but somehow it still works - presumably with some non open-sourced logic - for some cases)

**Comment by MrChrisW** [comment] 2016-01-04 12:32
@peterakkies Closing this now as unable to reproduce, please re-open if you notice the issue again. 


@marianosimone 
>I'm not sure I understand what's going on, but it seems like this IA was disabled ba91e55

This IA is triggered using "deep triggers" unfortunately this is not well documented. This means the IA is triggered using internal logic based on the returned search results.

**Closed by MrChrisW** 2016-01-04 12:32 UTC
Labels: Triggering
