### ISSUE TITLE
XKCD: &ia=comics not automaticlly showing up

### ISSUE THREAD

**Issue by Droobledores** [duckduckgo/zeroclickinfo-spice#3486] opened 2018-01-19 14:02 UTC
When I click on "Random", it brings up a regular search page WITHOUT the &ia=comics in the address bar. I am using version 62.0.3202.97 of Google Chrome. Please fix!

------
IA Page:  http://duck.co/ia/view/xkcd 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

**Comment by Droobledores** [comment] 2018-01-19 14:53
P.S. I reposted this because no one was assigned automatically

**Comment by moollaza** [comment] 2018-01-19 19:35
@Droobledores  I'm unable to reproduce this. The 'Random' link for me is a URL to a search on duckduckgo.com for "XKCD {random number}" and works as expected.

Are you still seeing this? Do you have any plugins enabled that might be modifying URLs?

**Comment by Droobledores** [comment] 2018-02-02 18:10
Sorry for the wait.
Yes, that is what I see and I am wondering if it is a glitch because sometimes &ia=comics shows up in the link and sometimes it doesn't.

Thanks

**Comment by moollaza** [comment] 2018-02-14 20:42
@Droobledores including `&ia=comics` in the url shouldn't be required. This IA triggers on the term XKCD so it should always show up.

Seeing as it is a non-critical issue I will close this and mark as tolerated.

**Closed by moollaza** 2018-02-14 20:42 UTC
