### ISSUE TITLE
Air Quality Index: Wrong location / zip code match

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-spice#2043] opened 2015-07-16 23:41 UTC
aqi 96161 is showing Tahoe City as the location (which is 96146)

Truckee is 96161.

![screen shot 2015-07-16 at 2 34 05 pm](https://cloud.githubusercontent.com/assets/7061920/8737679/badfeed0-2bd9-11e5-8a95-70b52361833a.png)

IA Page:  http://duck.co/ia/view/aqi

**Comment by gokul1794** [comment] 2015-07-17 12:38
This can be closed as it's a duplicate of #2042.

**Closed** 2015-07-27 22:07 UTC
