### ISSUE TITLE
Quixey: Multiple buttons getting displayed

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-spice#773] opened 2014-05-16 22:07 UTC
![screen shot 2014-05-16 at 6 05 52 pm](https://cloud.githubusercontent.com/assets/81969/3002850/6ef2a8f6-dd46-11e3-901f-70f220b71a34.png)

https://duck.co/ia/view/quixey

**Comment by MrChrisW** [comment] 2016-01-05 15:30
Closing as unable to reproduce. 

Tested with multiple search quires and no duplicate buttons were returned. 

Example : https://duckduckgo.com/?q=app+flightaware&ia=apps&iai=FlightAware+Flight+Tracker

Please re-open if able to reproduce this issue,

**Closed by MrChrisW** 2016-01-05 15:30 UTC
Labels: Bug
