### ISSUE TITLE
Time: No results returned for "New York"

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-spice#2083] opened 2015-08-10 17:45 UTC
https://duckduckgo.com/?q=time+in+new+york
https://duckduckgo.com/?q=time+in+new+york+city
https://duckduckgo.com/?q=time+in+nyc
https://duckduckgo.com/?q=time+in+new+york%2C+ny

------
IA Page:  http://duck.co/ia/view/time

**Comment by yegg** [comment] 2015-12-10 15:35
I got another report of this just now, FYI.

**Comment by marianosimone** [comment] 2015-12-28 01:39
Using duckpan, this can be explained because the Time IA only looks into the [capitals.yml](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/time/capitals.yml) file, that doesn't include non-capital cities like NY.

However, in production, other cities that are not in that file (e.g. Melbourne), do get an IA response. Is there any difference in the environments related to that?

**Comment by MrChrisW** [comment] 2016-01-04 12:24
>However, in production, other cities that are not in that file (e.g. Melbourne), do get an IA response. Is there any difference in the environments related to that?

@marianosimone duckduckgo.com uses deep triggers for the site timeanddate.com appearing in SERP results to trigger/display the IA. 

@bsstoner There's a few other queries that are having issues triggering, this is all caused by relevancy checking as the API does return data. We need to have a serious look at getting the Time IA updated to fix these issues. I'll close this now and keep track of things in #1730 thanks

**Closed by MrChrisW** 2016-01-04 12:24 UTC
Labels: Bug, Triggering
