### ISSUE TITLE
Time: Display time based on timezones

### ISSUE THREAD

**Issue by skeuomorf** [duckduckgo/zeroclickinfo-spice#2545] opened 2016-03-01 23:45 UTC
@MrChrisW Currently, queries like "time EST" won't trigger the time IA, which I think might be useful. If this is implemented, it'd be very cool if there were support for queries like "time Cairo to EST" which will display the current time in both Cairo and EST.

------
IA Page:  http://duck.co/ia/view/time

**Comment by MrChrisW** [comment] 2016-03-02 00:09
@skeuomorf Thanks for the suggestion. This is definitely a feature that would be great to implement.

While the upstream API (TimeandDate) does offer [time convert](services.timeanddate.com/api/services/converttime.html) functionality - It's a little difficult for the IA to convert a timezone "name" to a location ID which is accepted by the API. We do this manually at the moment https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/time/capitals.yml

We could look at adding Time Zone names to the capitals.yml file. :+1:

**Comment by MrChrisW** [comment] 2016-03-12 09:14
Hey @skeuomorf I'm closing this now as the issue is covered under https://github.com/duckduckgo/zeroclickinfo-spice/issues/1802 

Feel free to lodge a new issue if you find anything else that could do with improving! Thanks

**Closed by MrChrisW** 2016-03-12 09:14 UTC
Labels: Improvement, Suggestion

**Comment by skeuomorf** [comment] 2016-03-13 08:45
Fantastic, thanks for your work!
