### ISSUE TITLE
Currency: Doesn't trigger when "$" in query?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#1532] opened 2015-02-14 00:55 UTC
https://duckduckgo.com/?q=%24118+USD+to+CAD

This should definitely be triggering the Currency Spice and showing a result

**Comment by MrChrisW** [comment] 2015-02-14 01:34
@moollaza This is a duplicate of #1175 I'll happly take this one on!

**Comment by moollaza** [comment] 2015-02-14 04:39
@MrChrisW thanks for pointing that out!

**Closed** 2015-02-14 04:39 UTC
Labels: Bug, Priority: High, Triggering
