### ISSUE TITLE
PeopleInSpace: Country Flag shown wrongly

### ISSUE THREAD

**Issue by veeven** [duckduckgo/zeroclickinfo-spice#2366] opened 2015-12-31 10:51 UTC
@elebow

Astronaut Tim Peake's country is England. But, in instant answers it shows India flag (or rather, user's region flag). When I turned off my region setting, the flag shows as generic globe icon.

------
IA Page:  http://duck.co/ia/view/people_in_space

**Comment by veeven** [comment] 2015-12-31 10:52
I guess [this change](https://github.com/duckduckgo/zeroclickinfo-spice/commit/6447e8bffbbdd7cd5c9f53e5693d198fadb3bf94) is not live yet.

**Comment by MrChrisW** [comment] 2016-01-04 12:10
Duplicate of #2345

Hi @veeven, looks like the commit 27517f5 has yet to be included in a [release](https://github.com/duckduckgo/zeroclickinfo-spice/releases)  - this should happen soon, with a new release. Then the changes will be live on DuckDuckGo.com

Thanks!

**Closed by MrChrisW** 2016-01-04 12:10 UTC
