### ISSUE TITLE
Overlapping of Images with infomation

### ISSUE THREAD

**Issue by sagarhani** [duckduckgo/zeroclickinfo-spice#2058] opened 2015-07-27 19:47 UTC
![duckduckgo](https://cloud.githubusercontent.com/assets/6933389/8915942/b7c29ae6-34c5-11e5-9ad9-444f56c437a7.png)

Check this screenshot. The image of country which is behind the information is overlapping with the text which is at front. That's the reason the text developer is not visible properly.

**Comment by mattr555** [comment] 2015-07-27 22:18
Closing as duplicate of #2053, should be fixed in the next release!

**Closed by mattr555** 2015-07-27 22:18 UTC
