### ISSUE TITLE
Currency Conversion: 

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3624] opened 2020-10-28 21:21 UTC
When trying to convert BYN (New Belarusian ruble) the conversion is for BYR (obsolete Belarusian ruble).

![image](https://user-images.githubusercontent.com/6061680/97498120-ff327e80-1941-11eb-8460-3a66e2669f28.png)

------
IA Page:  http://duck.co/ia/view/currency 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment] 2020-10-28 21:26
@x-15a2 looks like this is a duplicate of #3405

It's a known issue, but the issue is upstream with the XE API.

An XE rep reached out recently to me and I've been waiting to hear back from them regarding a fix in the API.

**Comment by ascrazy** [comment] 2022-01-06 18:44
The bug is still there. Any plans to finally fix it?

**Closed** 2022-10-14 17:14 UTC
Labels: Bug
