### ISSUE TITLE
Random Words: 

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-spice#3467] opened 2017-12-06 11:17 UTC
Random words IA is not working, no IA interface is displayed and no random words are generated.

------
IA Page:  http://duck.co/ia/view/rand_word 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

**Comment by moollaza** [comment] 2017-12-06 14:43
Thanks for bringing this up. I will fix.

Duplicate of #3466

**Closed by moollaza** 2017-12-06 14:43 UTC
